sudo: false
language: node_js
node_js:
- '10.0.0'
before_install:
- npm i -g npm@6.4.1
- npm install -g typescript
stages:
- test
jobs:
  include:
  - stage: test
    name: "Lint and Tests"
    script:
    - npm run lint
    - npm run test
